### ISSUE TITLE
Exception: Can't open or download 'a52dec' package, check your internet connection

### ISSUE THREAD

**Issue by Axeltherabbit** [droserasprout/pacman-fix-permissions#8]
```
$> sudo python pacman-fix-permissions 
Namespace(all=False, filesystem_paths=None, packages=None)
==> Upgrading packages that are out-of-date
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Synchronizing package databases...
 core                                                                     131.6 KiB   940 KiB/s 00:00 [############################################################] 100%
 extra                                                                   1663.7 KiB   685 KiB/s 00:02 [############################################################] 100%
 community                                                                  5.2 MiB  1012 KiB/s 00:05 [############################################################] 100%
 multilib                                                                 158.7 KiB  2.01 MiB/s 00:00 [############################################################] 100%
:: Starting full system upgrade...
 there is nothing to do
==> Parsing installed packages list
==> Collecting actual filesystem permissions and correct ones from packages
(1/1034) a52dec 0.7.4-11
=> a52dec package is missing, downloading
Traceback (most recent call last):
  File "pacman-fix-permissions", line 105, in <module>
    main()
  File "pacman-fix-permissions", line 75, in main
    pkgtar = getTar(pkgs[i])
  File "pacman-fix-permissions", line 47, in getTar
    raise Exception("Can't open or download '{}' package, check your internet connection".format(pkg[0]))
Exception: Can't open or download 'a52dec' package, check your internet connection
```

My connection is fine, probably is just not finding the package to download for some reason, I will try to fix this.

**Comment by s-ol** [comment]
The script currently assumes that packages are compressed using `xz` (`.tar.xz`), but Arch Linux recently switched to use `zstd` (`.tar.zst`) as the default. I just hit the same issue and will add a PR shortly :slightly_smiling_face:
